---
- name: src-host - Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: src-host - Upgrade APT to the latest packages
  apt:
    upgrade: "yes"

- name: src-host - Update all packages to the latest version
  apt:
    upgrade: dist

- name: src-host - Reboot host
  reboot:
    reboot_timeout: 600
