---
- name: Start prysm-docker-compose except validator and slasher
  shell: "docker-compose up -d {{ item }}"
  args:
    chdir: "{{ prysm_install_path }}"
  with_items: "{{ starting_containers | difference(['slasher']) }}"

- name: Give services time to spinn up
  pause:
    minutes: 1

- name: Check health of beacon service
  uri:
    url: "http://{{eth2node_ha_ip}}:8480/healthz"
    return_content: yes
  register: result
  until: "result.status == 200 and 'error' not in result.content"
  retries: 1200
  delay: 3
  when: "'beacon' in starting_containers"

- name: Start slasher
  shell: "docker-compose up -d slasher"
  args:
    chdir: "{{ prysm_install_path }}"
  when: "'slasher' in starting_containers"

- name: Give slasher service time to spinn up
  pause:
    minutes: 1
  when: "'slasher' in starting_containers"

- name: Check health of slasher service
  uri:
    url: "http://{{eth2node_ha_ip}}:8680/healthz"
    return_content: yes
  register: result
  until: "result.status == 200 and 'error' not in result.content"
  retries: 600
  delay: 3
  when: "'slasher' in starting_containers"

- name: Start validators
  shell: "docker-compose stop validator && docker-compose up -d validator"
  args:
    chdir: "{{ prysm_install_path }}"
  when: hostvars[inventory_hostname].starting_validator

- name: Give validator service time to spinn up
  pause:
    minutes: 1
  when: hostvars[inventory_hostname].starting_validator

- name: Check health of validator service
  uri:
    url: "http://{{eth2node_ha_ip}}:8580/healthz"
    return_content: yes
  register: result
  until: "result.status == 200 and 'error' not in result.content"
  retries: 600
  delay: 3
  when: hostvars[inventory_hostname].starting_validator
