---
- hosts: all
  become: yes
  vars:
    metricbeat_yml: /etc/metricbeat/metricbeat.yml
    metricbeat_docker_yml: /etc/metricbeat/modules.d/docker.yml
    metricbeat_system_yml: /etc/metricbeat/modules.d/system.yml
    metricbeat_kibana: localhost:5601
    metricbeat_version: 7.7.1
  
  roles:
  - metricbeat

  handlers:
  - name: Restart metricbeat
    service: 
      name: metricbeat
      enabled: yes
      state: restarted