---
- hosts: all
  become: yes
  vars:
    metricbeat_yml: /etc/metricbeat/metricbeat.yml
    metricbeat_connection: localhost:9200
    metricbeat_version: 7.7.1
  
  roles:
  - metricbeat

  handlers:
  - name: Restart metricbeat
    service: 
      name: metricbeat
      enabled: yes
      state: restarted