---
- name: Generate HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: "{{ prysm_install_path }}/config/ha/haproxy.cfg"
    owner: "{{ prysm_user }}"
    group: "{{ prysm_user }}"
    mode: 0644

- name: Generate docker-compose overrice file
  template:
    src: docker-compose.override.yaml.j2
    dest: "{{ prysm_install_path }}/docker-compose.override.yaml"
    owner: "{{ prysm_user }}"
    group: "{{ prysm_user }}"
    mode: 0644

- name: Stop services
  shell: docker-compose down
  args:
    chdir: "{{ prysm_install_path }}"

- name: Start serivces (except validator)
  command: docker-compose up -d {{ hostvars[inventory_hostname].eth2node_ha_start_services|join(' ') }}
  args:
    chdir: "{{ prysm_install_path }}"