---
- name: Generate account name
  set_fact:
    new_validator_name: "{{ validator_wallet_name }}/{{ 9999999999999999999999 | random | to_uuid }}"

- name: Create account
  command: /home/{{ prysm_user }}/go/bin/ethdo account create --account="{{ new_validator_name }}" --walletpassphrase="{{ validator_wallet_password }}"  --passphrase="{{ validator_accounts_password }}"
  
- name: Get deposit data
  command: /home/{{ prysm_user }}/go/bin/ethdo validator depositdata --withdrawalaccount="{{ withdrawal_wallet_name }}/{{ withdrawal_account_name }}" --validatoraccount="{{ new_validator_name }}"  --depositvalue=32000000000000000000 --raw --passphrase="{{ validator_accounts_password }}" --forkversion="{{ validator_forkversion }}"
  register: deposit_data_raw
  
- name: Save deposit data
  lineinfile:
    path: /home/{{ prysm_user }}/depositdata
    line: "{{ deposit_data_raw.stdout }}"
    create: yes
