---
- name: Create validator accounts
  include_tasks: create-validator-account.yaml
  loop: "{{ query('sequence', 'start=1 end='+validator_accounts|string) }}"

- name: Locate validator wallet
  command: /home/{{ prysm_user }}/go/bin/ethdo wallet info --wallet="{{ validator_wallet_name }}" --verbose
  register: wallet_info

- name: Copy validator wallet to validator's datadir
  command: cp -R "{{ item.split(' ')[1] }}" "{{ prysm_install_path }}/validator/"
  with_items: "{{ wallet_info.stdout.splitlines()|select('match', '^Location')|list }}"
  
