---
- name: Create file
  file:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    state: touch

- name: Prepare beginning of file's content (json)
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: >
           {
             "location": "/data",
             "accounts": [
             
- name: Appending validators' names
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "\"{{ validator_wallet_name}}/*\""

- name: Prepare password list
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "],\"passphrases\": ["

- name: Appending validators' passwords
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "\"{{ validator_accounts_password }}\""

- name: Finish file's content (json)
  lineinfile:
    path: /home/{{ prysm_user }}/keystoreWallet.json
    line: "]}"

- name: Put keystore into place (move file)
  shell: mv /home/{{ prysm_user }}/keystoreWallet.json {{ prysm_install_path }}/validator/keystoreWallet.json

- name: Adapt docker-compose.yaml to use config file for keystoreWallet.json
  lineinfile:
    path: "{{ prysm_install_path }}/docker-compose.yaml"
    regexp: "\\-\\s\\.\\/config\\/validator\\.yaml\\:\\/config\\/validator\\.yaml"
    line: "                        - ./config/validator-wallet.yaml:/config/validator.yaml:ro"
    backrefs: yes