---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
  - git
  - vim
  become: yes

- name: Clone Ethereum 2.0 docker compose setup
  git:
    repo: "https://github.com/stefa2k/prysm-docker-compose"
    dest: "{{ prysm_install_path }}"
  become: yes

- name: Change file ownership and group of clone
  file:
    state: directory
    path: "{{ prysm_install_path }}"
    owner: "{{ prysm_user }}"
    group: "{{ prysm_user }}"
    recurse: yes
  become: yes

- name: Configure correct IP address for node
  lineinfile:
    path: "{{ prysm_install_path }}/config/beacon.yaml"
    regexp: '^p2p-host-ip: '
    line: 'p2p-host-ip: {{ ansible_default_ipv4.address }}'



